### ISSUE TITLE
There's no way to have optional segment separators 

### ISSUE THREAD

**Issue by tomnomnom** [tomnomnom/unfurl#1]
E.g. when you do this:

```
▶ cat urls.txt | unfurl -u format "%p?%q#%f"
/users?id=123&name=Sam#
/orgs?org=ExCo#about
/about?#contact
```

You end up with `?` and `#` chars where they're not needed.

It would be good to create format directives to help with this. Probably something like:

```
%?  Inserts a '?' if there is a query string
%#  Inserts a '#' if there is a page fragment
```

**Comment by cmbuckley** [comment]
Adding `%:` - Inserts a `:` if there is a port

**Comment by tomnomnom** [comment]
@cmbuckley that one too, yes! Thanks :)

Will also need `%@` once creds (`...user:pass@domain...`) are supported - I've raised #3 for that not being supported

**Comment by cmbuckley** [comment]
Suggest at that point that `%a` (authority) becomes shorthand for `%u%@%d%:%P` :-)

**Comment by tomnomnom** [comment]
Those kinds of shorthand are definitely a good idea and something I had in mind :)
