### ISSUE TITLE
Unexpected response for .za domains

### ISSUE THREAD

**Issue by JeffreyShran** [tomnomnom/unfurl#11]
I would expect both of these to use `site` as the root - probably easier to demonstrate with an example:

**Unexpected result:**
```
echo "www.site.co.za" | unfurl format %r.%t
za.co.za
```
**Expected Result**
```
echo "www.site.co.jp" | unfurl format %r.%t
site.co.jp
```

In the first example `unfurl` repeats "za" for some reason?

**Comment by tomnomnom** [comment]
Hey! This is exactly how the tool works now that it uses a list of known TLDs to aid in the parsing:

```
tom@girru:~▶ echo "www.site.co.za" | unfurl format %r.%t
site.co.za
tom@girru:~▶ echo "www.site.co.jp" | unfurl format %r.%t
site.co.jp
```

Update to the latest version and let me know if you have any more problems :)

As an aside, I noticed using `format %r.%t` was a super common use-case so I've added the `apex` mode in the latest version too:

```
tom@girru:~▶ echo "www.site.co.jp" | unfurl apex
site.co.jp
```

**Comment by JeffreyShran** [comment]
Awesome. Thanks buddy :)
