### ISSUE TITLE
Third level domain option?

### ISSUE THREAD

**Issue by roarnyg** [tomnomnom/unfurl#12]
I would love if I could get third level domain names, for example xibo.co.uk. 

There are some domains that "always" has three levels in their domain names, co.uk, com.br, com.ar, etc. How can I extract those?

**Comment by roarnyg** [comment]
%r  The root of domain (e.g. example)
%t  The TLD (e.g. com)

Example:
echo xibo.co.uk | unfurl format %r
_co_

The output should be 
_xibo_

The %t only gives the value
_uk_
while 
_co.uk_ 
would be expected.

**Comment by tomnomnom** [comment]
Hey! Thanks for raising an issue :)

This is indeed how the tool works now:
![Screenshot from 2022-04-06 11-47-10](https://user-images.githubusercontent.com/58276/161958443-5abebfbf-308c-48ee-946f-abb1e47a2f9c.png)

Let me know if you're still having problems
