### ISSUE TITLE
Unique path patterns

### ISSUE THREAD

**Issue by luchua-bc** [tomnomnom/unfurl#13]
Hi @tomnomnom,

The tool is great and very helpful.

I have one feature request for consideration of future releases. Frequently the source are wayback urls, which have many similar unique urls but don't make a difference for security testing.

For example, I would only want to include one of the following two urls:
```
https://www.example.com/path?param1=a&param2=b&param3=c
https://www.example.com/path?param1=c&param2=d&param3=e
```

However, the following is to be included:
```
https://www.example.com/path?param1=a&param2=b
https://www.example.com/path?param4=a&param5=b&param6=c
https://www.example.com/path2?param1=a&param2=b&param3=c
https://www.example2.com/path?param1=a&param2=b&param3=c
``` 
That is, only unique combinations of domain, path, and keys are to be included (not values of keys). This will help to reduce processing time of subsequent testing steps.

Does this make sense? Please advise. Thanks.

**Comment by tomnomnom** [comment]
That does make sense! This is actually possible already with the [qsreplace](https://github.com/tomnomnom/qsreplace) tool, by supplying the `-a` flag with no parameter (see [here](https://github.com/tomnomnom/qsreplace#remove-duplicate-url-and-parameter-combinations) for an example.

Part of me has considered rolling qsreplace's functionality into unfurl, so I will give that some more thought. Thanks!
