### ISSUE TITLE
Fatal Error

### ISSUE THREAD

**Issue by logm1lo** [tomnomnom/unfurl#14]
Hi, when I run unfurl, it gives this error:

```
❯ unfurl
fatal error: runtime: bsdthread_register error

runtime stack:
runtime.throw(0x12b0321, 0x21)
	/usr/local/go/src/runtime/panic.go:619 +0x81 fp=0x7ff7bfeff8e8 sp=0x7ff7bfeff8c8 pc=0x1028a61
runtime.goenvs()
	/usr/local/go/src/runtime/os_darwin.go:129 +0x83 fp=0x7ff7bfeff918 sp=0x7ff7bfeff8e8 pc=0x10265e3
runtime.schedinit()
	/usr/local/go/src/runtime/proc.go:496 +0xa4 fp=0x7ff7bfeff970 sp=0x7ff7bfeff918 pc=0x102b324
runtime.rt0_go(0x7ff7bfeff9a0, 0x1, 0x7ff7bfeff9a0, 0x1000000, 0x1, 0x7ff7bfeffb08, 0x0, 0x7ff7bfeffb0f, 0x7ff7bfeffb48, 0x7ff7bfeffb70, ...)
	/usr/local/go/src/runtime/asm_amd64.s:252 +0x1f4 fp=0x7ff7bfeff978 sp=0x7ff7bfeff970 pc=0x1050f54


```
Please help me fix this error

**Comment by tomnomnom** [comment]
Hi there,

Can you let me know what operating system you're using, and what version of unfurl you are using (i.e. did you download a binary or build it from source? If you are using a binary, which one?)

**Comment by logm1lo** [comment]
> Hi there,
> 
> Can you let me know what operating system you're using, and what version of unfurl you are using (i.e. did you download a binary or build it from source? If you are using a binary, which one?)

Sorry for my late reply, but after I downloaded Go from the website, not from apt, It worked!
