### ISSUE TITLE
Clarification on handling empty values

### ISSUE THREAD

**Issue by cmbuckley** [tomnomnom/unfurl#2]
This may be desired behaviour, but the readme should call it out if so:

An empty output for given format results in no output for that value, rather than an empty line:

```
cat urls.txt
http://example.net/about#contact
http://example.net:80/about#contact
http://example.net:8080/about#contact

cat urls.txt | unfurl format %P
80
8080
```

**Comment by tomnomnom** [comment]
Yeah, that is intended behaviour. It's done [here](https://github.com/tomnomnom/unfurl/blob/19d91dbfe375b2623cc52f629b125d2630a30789/main.go#L59-L62).

I'll add something to the readme to clarify, thanks :)
