### ISSUE TITLE
unfurl not support parsing the ext

### ISSUE THREAD

**Issue by 0ktavandi** [tomnomnom/unfurl#9]
unfurl not support parsing the extension mode
if any url like this `example.com/asdasda.jpg`

how unfurl extract the extension in unfurl mode? 
so the expected output will be 
`echo example.com/crot.jpg | unfurl extension`
> jpg

**Comment by tomnomnom** [comment]
Good idea!

I've implemented this as a format specifier so you can do:

```
> echo example.com/crot.jpg | unfurl format %e
jpg
```
This is available from [v0.3.1](https://github.com/tomnomnom/unfurl/releases/tag/v0.3.1)

If it seems to be popular I'll add an `extension` alias to make it easier. Thanks!
